-- DATA MIGRATION: Consolidate material_issues to one record per vehicle per FY
-- Must run BEFORE the UNIQUE constraint is added below.

-- Step 1: Delete all Draft slips — they have zero stock deductions, safe to remove
DELETE FROM "material_issues" WHERE "status" = 'Draft';--> statement-breakpoint

-- Step 2: Delete items from non-canonical slips where the same material_id already
-- exists in the canonical (most recently updated) slip for that vehicle/type/FY.
-- "Latest slip wins" — canonical items are kept; duplicates from older slips are dropped.
WITH canonical AS (
  SELECT DISTINCT ON (vehicle_id, issue_type, financial_year)
    id AS canonical_id, vehicle_id, issue_type, financial_year
  FROM material_issues
  ORDER BY vehicle_id, issue_type, financial_year, updated_at DESC
),
non_canonical AS (
  SELECT mi.id AS nc_id, c.canonical_id
  FROM material_issues mi
  JOIN canonical c
    ON mi.vehicle_id = c.vehicle_id
    AND mi.issue_type = c.issue_type
    AND mi.financial_year = c.financial_year
    AND mi.id <> c.canonical_id
)
DELETE FROM material_issue_items
WHERE id IN (
  SELECT mii.id
  FROM material_issue_items mii
  JOIN non_canonical nc ON mii.issue_id = nc.nc_id
  WHERE EXISTS (
    SELECT 1 FROM material_issue_items mii2
    WHERE mii2.issue_id = nc.canonical_id
    AND mii2.material_id = mii.material_id
  )
);--> statement-breakpoint

-- Step 3: Move remaining items from non-canonical slips to their canonical record
WITH canonical AS (
  SELECT DISTINCT ON (vehicle_id, issue_type, financial_year)
    id AS canonical_id, vehicle_id, issue_type, financial_year
  FROM material_issues
  ORDER BY vehicle_id, issue_type, financial_year, updated_at DESC
),
non_canonical AS (
  SELECT mi.id AS nc_id, c.canonical_id
  FROM material_issues mi
  JOIN canonical c
    ON mi.vehicle_id = c.vehicle_id
    AND mi.issue_type = c.issue_type
    AND mi.financial_year = c.financial_year
    AND mi.id <> c.canonical_id
)
UPDATE material_issue_items
SET issue_id = nc.canonical_id
FROM non_canonical nc
WHERE material_issue_items.issue_id = nc.nc_id;--> statement-breakpoint

-- Step 4: Update invoice_slip_links — delete links that would become duplicate
-- (invoice already linked to the canonical record)
WITH canonical AS (
  SELECT DISTINCT ON (vehicle_id, issue_type, financial_year)
    id AS canonical_id, vehicle_id, issue_type, financial_year
  FROM material_issues
  ORDER BY vehicle_id, issue_type, financial_year, updated_at DESC
),
non_canonical AS (
  SELECT mi.id AS nc_id, c.canonical_id
  FROM material_issues mi
  JOIN canonical c
    ON mi.vehicle_id = c.vehicle_id
    AND mi.issue_type = c.issue_type
    AND mi.financial_year = c.financial_year
    AND mi.id <> c.canonical_id
)
DELETE FROM invoice_slip_links
WHERE id IN (
  SELECT isl.id
  FROM invoice_slip_links isl
  JOIN non_canonical nc ON isl.slip_id = nc.nc_id
  WHERE EXISTS (
    SELECT 1 FROM invoice_slip_links isl2
    WHERE isl2.invoice_id = isl.invoice_id
    AND isl2.slip_id = nc.canonical_id
  )
);--> statement-breakpoint

-- Step 5: Remap remaining invoice_slip_links to canonical records
WITH canonical AS (
  SELECT DISTINCT ON (vehicle_id, issue_type, financial_year)
    id AS canonical_id, vehicle_id, issue_type, financial_year
  FROM material_issues
  ORDER BY vehicle_id, issue_type, financial_year, updated_at DESC
),
non_canonical AS (
  SELECT mi.id AS nc_id, c.canonical_id
  FROM material_issues mi
  JOIN canonical c
    ON mi.vehicle_id = c.vehicle_id
    AND mi.issue_type = c.issue_type
    AND mi.financial_year = c.financial_year
    AND mi.id <> c.canonical_id
)
UPDATE invoice_slip_links
SET slip_id = nc.canonical_id
FROM non_canonical nc
WHERE invoice_slip_links.slip_id = nc.nc_id;--> statement-breakpoint

-- Step 6: Delete non-canonical material_issues records (now empty of items)
WITH canonical AS (
  SELECT DISTINCT ON (vehicle_id, issue_type, financial_year) id
  FROM material_issues
  ORDER BY vehicle_id, issue_type, financial_year, updated_at DESC
)
DELETE FROM material_issues
WHERE id NOT IN (SELECT id FROM canonical);--> statement-breakpoint

-- SCHEMA CHANGES (auto-generated by drizzle-kit)
ALTER TABLE "material_issues" DROP CONSTRAINT "slip_number_fy_unique";--> statement-breakpoint
ALTER TABLE "material_issues" ALTER COLUMN "slip_number" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "material_issues" ADD CONSTRAINT "mi_vehicle_type_fy_unique" UNIQUE("vehicle_id","issue_type","financial_year");
